# xiaozhi-serverを軽量インストールしたい場合、ローカルの設定ファイルのみを使用する場合は、このファイルを無視してください。何も変更する必要はありません
# manager-apiから設定を取得したい場合は、以下の手順に従ってください:
# 1. このファイルをxiaozhi-server/dataディレクトリにコピーし、名前を.config.yamlに変更してください（dataディレクトリがない場合は作成してください）
# 2. dataディレクトリに既に.config.yamlファイルがある場合は、先に削除してください
# 3. manager-apiとmanager-webを起動し、アカウントを登録してください（最初に登録したアカウントが管理者になります）
# 4. 管理者アカウントで「パラメータ管理」ページに移動し、「server.secret」を見つけて、その値をコピーしてください（ゼロからデプロイするたびにserver.secretは変化します）
# 5. dataディレクトリの.config.yamlファイルを開き、manager-api.secretを先ほどコピーしたserver.secretに変更してください
server:
  ip: 0.0.0.0
  port: 8000
  # HTTPサービスのポート（視覚分析インターフェース用）
  http_port: 8003
  # 視覚分析インターフェースアドレス
  # デバイスに送信する視覚分析のインターフェースアドレス
  # 以下のデフォルト設定のままにすると、システムは自動的に視覚認識アドレスを生成し、起動ログに出力します。このアドレスはブラウザで直接確認できます
  # Dockerでデプロイする場合や公網デプロイ（SSL/ドメイン使用）の場合、正確でない可能性があります
  # そのため、Dockerでデプロイする場合はvision_explainをLANアドレスに設定してください
  # 公網でデプロイする場合はvision_explainを公網アドレスに設定してください
  vision_explain: http://あなたのIPまたはドメイン:ポート番号/mcp/vision/explain
manager-api:
  # manager-apiのアドレス（LAN IPを使用するのが最適です）
  # Dockerでデプロイする場合は http://xiaozhi-esp32-server-web:8002/xiaozhi と記入してください
  url: http://127.0.0.1:8002/xiaozhi
  # manager-apiのトークン（先ほどコピーしたserver.secret）
  secret: あなたのserver.secret値